# action.yml
name: 'ECS deploy with Region'
description: 'Github action using fabfuel/ecs-deploy script for ecs deployments'
inputs:
    cluster:
        description: 'Cluster name where service/task will be deployed'
        required: true
    service:
        description: 'Service name of the service/task to be deployed'
        required: true
    task:
        description: 'Task definition name to be updated'
        required: true
    container:
        description: 'Container name to be updated'
        required: true
    region:
        description: 'Region to deploy in'
        required: true
    envfile:
        description: 'Env file path'
        required: false
    timeout:
        description: 'Deployment timeout (default 300)'
        required: false      
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.access_key }}
    - ${{ inputs.secret_key }}
    - ${{ inputs.region }}
    - ${{ inputs.cluster }}
    - ${{ inputs.service }}
    - ${{ inputs.task }}
    - ${{ inputs.container }}
    - ${{ inputs.envfile }}
    - ${{ inputs.timeout }}
